### ISSUE TITLE
svg not parsable into svg editor

### ISSUE THREAD

**Issue by salamichel** [gliffy/canvas2svg#14]
Dear all 

I used following code (sample) 

var ctx = new C2S(500,500);
ctx.font = "normal 36px Times";
ctx.fillStyle = "#000000";
ctx.fillText("A Text Example", 50, 50);
ctx.font        = "normal 36px Arial";
ctx.strokeStyle = "#000000";
ctx.strokeText("A Text Example", 50, 90);
var svg = ctx.getSvg();
console.log(svg);

then I copy/paste the result below :

<svg version=​"1.1" xmlns=​"http:​/​/​www.w3.org/​2000/​svg" xmlns:xlink=​"http:​/​/​www.w3.org/​1999/​xlink" width=​"500" height=​"500">​<defs>​</defs>​<g>​<text fill=​"#000000" stroke=​"none" font-family=​"Times" font-size=​"36px" font-style=​"normal" font-weight=​"normal" text-decoration=​"none" x=​"50" y=​"50" text-anchor=​"start" dominant-baseline=​"alphabetic">​A Text Example​</text>​<text fill=​"none" stroke=​"#000000" font-family=​"Arial" font-size=​"36px" font-style=​"normal" font-weight=​"normal" text-decoration=​"none" x=​"50" y=​"90" text-anchor=​"start" dominant-baseline=​"alphabetic" stroke-miterlimit=​"10">​A Text Example​</text>​</g>​</svg>​

-> First of all, I do not get the same show in page http://gliffy.github.io/canvas2svg/ for simple example.
-> My output does not work when i copy/paste into SVG editor, 

Could you please help me

**Comment by gwwar** [comment]
Try calling `ctx.getSerializedSvg(true);` this should return well-formatted SVG output.

ctx.getSvg() returns svg nodes that were created in the page, which is mostly only useful if you're trying to manipulate the nodes on the html page.

**Comment by salamichel** [comment]
Thank for your reply, I found what goes wrong (copy/paste from chrome console add unexpected caracteres
regards
