### ISSUE TITLE
Multiple translates, rotations aren't right

### ISSUE THREAD

**Issue by gillescastel** [gliffy/canvas2svg#16]
What I get when I use canvas2svg:
![001056-](https://cloud.githubusercontent.com/assets/7069691/7145578/a295bd6c-e2ed-11e4-9248-4d638a4f3c5b.png)

What I get when I use canvas:
![001055-](https://cloud.githubusercontent.com/assets/7069691/7145582/a9bfbf20-e2ed-11e4-852e-3fb99e2477e7.png)

Code:
```javascript
ctx.fillRect(0, 0, 10, 10)
ctx.translate(0, 20)
ctx.fillRect(0, 0, 10, 10)
ctx.translate(0, 20)
ctx.fillRect(0, 0, 10, 10)
ctx.translate(0, 20)
```

The generated svg is:
![001057-ulamspiral html](https://cloud.githubusercontent.com/assets/7069691/7145625/f0293c66-e2ed-11e4-977b-fe54e6824817.png)

I have this problem too when I use `ctx.rotate()`

**Comment by gwwar** [comment]
I'll take a look this weekend

**Comment by gwwar** [comment]
Hi, @gillescastel thanks for reporting. I have a pr open for this, but if you can't wait, you can get the fix here: https://github.com/gwwar/canvas2svg

**Comment by gillescastel** [comment]
Thank you very much!
