### ISSUE TITLE
Invalid value for <path> attribute d=" L 30 20 C 80 0 80 75 30 75 C 50 80 60 25 30 20"

### ISSUE THREAD

**Issue by zenozeng** [gliffy/canvas2svg#21]
Hey, thanks for your great work. But I have encountered a bug.

```javascript
beginPath();
lineTo(30, 20);
bezierCurveTo(80, 0, 80, 75, 30, 75);
bezierCurveTo(50, 80, 60, 25, 30, 20);
fill();
stroke();
closePath();
```
The path generated is `L 30 20 C 80 0 80 75 30 75 C 50 80 60 25 30 20`, which actually should be `M 30 20 C 80 0 80 75 30 75 C 50 80 60 25 30 20`.

![2015-05-29 20 17 05](https://cloud.githubusercontent.com/assets/2544489/7886493/03b6e052-065d-11e5-9ef6-7a3b93f8be20.png)

According to W3's doc, Canvas's moveTo(x, y) method must create a new subpath with the specified point as its first (and only) point. And canvas's lineTo(x, y) method must ensure there is a subpath for (x, y) if the object's path has no subpaths. Otherwise, it must connect the last point in the subpath to the given point (x, y) using a straight line, and must then add the given point (x, y) to the subpath.

However, SVG's lineto only draw straight lines from the current point to a new point.

See also: http://www.w3.org/TR/2015/WD-2dcontext-20150514/#dom-context-2d-lineto

See also: http://www.w3.org/TR/SVG/paths.html#PathDataLinetoCommands

So in canvas2svg, when lineTo called, we should check if there is a subpath, and use `M x y` instead of `L x y` if the object's path has no subpaths.

This issue is fixed in https://github.com/zenozeng/canvas2svg/commit/1c49685c9d8caab0cbba14065aa193c4c623444c. But this fix need https://github.com/gliffy/canvas2svg/pull/20 to be merged. I will pull a new request for this issue as soon as pull#20 merged.

See also: https://github.com/zenozeng/p5.js-svg/issues/44

**Comment by clintjd** [comment]
I've merged #20.  Thanks!
