### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by ConradIrwin** [gliffy/canvas2svg#29]
Any chance you could put this up on NPM? Should just be a case of running `npm publish`. That would let me use it easily from webpack :).

**Comment by ConradIrwin** [comment]
For now I've pushed my fork to https://www.npmjs.com/package/canvas2svg-conradirwin to leave the main name open for this repo.

**Comment by clintjd** [comment]
Hi Conrad,

Let me get back to you on this.

Thanks,
Clint

**Comment by webspinner** [comment]
Published to npm now. Thanks for the hard work on this. https://www.npmjs.com/package/canvas2svg

**Comment by ConradIrwin** [comment]
Awesome, thanks! I'll update [canvas-animation-loader](https://github.com/ConradIrwin/canvas-animation-loader) to point to the main package.
