### ISSUE TITLE
Export Canvas Image to SVG

### ISSUE THREAD

**Issue by abureviewer3** [gliffy/canvas2svg#43]
Hi thank you for this great plugin its very useful for me in my project but I'm unable to find how to convert a rendered canvas image to SVG can you help me how to do this.

**Comment by durasj** [comment]
Hi, I am afraid that you can't "convert" a populated canvas as it's just a **bitmap** while SVG is **vector** format.

This library will just execute all the **commands** you do on canvas in "svg context". It doesn't (and can't) use **pixels** from bitmap output of canvas.

**Comment by jonathan-potter** [comment]
a very late thank you to @durasj for fielding this question ages ago.
