### ISSUE TITLE
filter and globalCompositeOperation are not working

### ISSUE THREAD

**Issue by rmcuevas** [gliffy/canvas2svg#80]
Make canvas with filter or globalCompositeOperation function.
Convert it into svg.

Expected: Canvas and svg output should be the same.
Actual: Svg output is different.

**Comment by ecstrema** [comment]
see https://github.com/gliffy/canvas2svg/blob/master/canvas2svg.js#L1201
global composite operation is not implemented yet. `filter` doesn't look implemented either.

**Comment by rmcuevas** [comment]
Yeah, but thankfully I made a work around for it. If there is anyone who is interested, just leave a comment.

**Comment by murkle** [comment]
I'm interested :)

**Comment by rmcuevas** [comment]
> I'm interested :)

You can add this line `context.filter = "grayscale(1)";` after line 1151 https://github.com/gliffy/canvas2svg/blob/master/canvas2svg.js

**Comment by murkle** [comment]
Thanks! So between
`                context = canvas.getContext("2d");
`
and
`                context.drawImage(image, sx, sy, sw, sh, 0, 0, dw, dh);
`

**Comment by rmcuevas** [comment]
Yes
