### ISSUE TITLE
Opacity not working

### ISSUE THREAD

**Issue by jeffThompson** [gliffy/canvas2svg#82]
OMG, thank you for such an awesome and helpful library! I'm connecting this with `chart.js` so the issue might be there, but I'm not getting opacity to carry through when exporting. For example, if I create a chart with semi-transparent bars, they show up onscreen correctly. But when exporting as an `svg` they come out opaque.

I am using [these tweaks suggested on SO](https://stackoverflow.com/questions/62249315/export-canvas-to-svg-file), so maybe the problem is coming from there too?

```
function tweakLib() {
	C2S.prototype.getContext = function(contextId) {
	    if (contextId === '2d' || contextId === '2D') {
	        return this;
	    }
	    return null;
	}
	C2S.prototype.style = function() {
	    return this.__canvas.style;
	}
	C2S.prototype.getAttribute = function(name) {
	    return this[name];
	}
	C2S.prototype.addEventListener = function(type, listener, eventListenerOptions) {
	    // nothing to do here, but we need this function :)
	}
}
```

Any pointers would be great – happy to fix and submit a PR!

**Comment by murkle** [comment]
Try this fork first: https://github.com/murkle/canvas2svg/ as it has quite a few fixes including opacity for images

If that doesn't help please post a minimal example to show the problem

**Comment by jeffThompson** [comment]
Thanks, that does seem to (mostly) solve it! I'll close this issue
